import { CurrencyPipe, NgClass, NgFor, NgIf } from '@angular/common';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lembrancinhas',
  standalone: true,
  imports: [NgClass, NgFor, NgIf, CurrencyPipe],
  templateUrl: './lembrancinhas.component.html',
  styleUrl: './lembrancinhas.component.css',
})
export class LembrancinhasComponent implements OnInit {
  listaLembrancinhas: any;

  ngOnInit(): void {
    this.listaLembrancinhas = [
      {
        id: 1,
        ativo: false,
        titulo: 'Brigadeiro Decorado',
        descricao: null,
        valor: 2.5  ,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/01.jpeg',
        recheio: null,
      },
      {
        id: 2,
        ativo: false,
        titulo: 'Bombons',
        descricao: null,
        valor: 3,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/02.jpeg',
        recheio: null,
      },
      {
        id: 3,
        ativo: false,
        titulo: 'Tabletinho de chocolate',
        descricao: null,
        valor: 3,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/03.jpeg',
        recheio: null,
      },

      {
        id: 4,
        ativo: false,
        titulo: 'Mini ovo',
        descricao: null,
        valor: 3.5,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/04.jpeg',
        recheio: null,
      },
      {
        id: 5,
        ativo: false,
        titulo: 'Cenourito',
        descricao: 'Casquinha de chocolate com brigadeiro e bolo de cenoura',
        valor: 3,
        peso: 30,
        valor2: 5.5,
        peso2: 70,
        valor3: 12,
        peso3: 140,
        urlFoto: 'assets/lembrancinhas2026/05.jpeg',
        recheio: null,
      },
      {
        id: 6,
        ativo: false,
        titulo: 'Coelho de Chocolate',
        descricao: null,
        valor: 7,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/06.jpeg',
        recheio: null,
      },
      {
        id: 7,
        ativo: false,
        titulo: 'Ovo Frito 1',
        descricao: null,
        valor: 7,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/07.jpeg',
        recheio: null,
      },
      {
        id: 8,
        ativo: false,
        titulo: 'Ovo Frito 2',
        descricao: null,
        valor: 10,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/08.jpeg',
        recheio: null,
      },
      {
        id: 9,
        ativo: false,
        titulo: 'Controle recheado com Ninho e Nutella',
        descricao: null,
        valor: 12,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/09.jpeg',
        recheio: null,
      },
      {
        id: 10,
        ativo: false,
        titulo: 'Dois mini ovos recheados',
        descricao: null,
        descricao2: null,
        valor: 14,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/10.jpeg',
        recheio: null,
      },
      {
        id: 11,
        ativo: false,
        titulo: 'Trio de Mini Ovos Recheados e Sortidos',
        descricao: null,
        descricao2: null,
        valor: 23,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/11.jpeg',
        recheio: null,
      },
      {
        id: 12,
        ativo: false,
        titulo: 'Tablete de chocolate recheado',
        descricao: null,
        descricao2: null,
        valor: 28,
        peso: 200,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2026/12.jpeg',
        recheio: ['Cocadinha ou Brigadeiro'],
      },
     
          ];
  }
}
