import { CurrencyPipe, NgClass, NgFor, NgIf } from '@angular/common';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lembrancinhas',
  standalone: true,
  imports: [NgClass, NgFor, NgIf, CurrencyPipe],
  templateUrl: './lembrancinhas.component.html',
  styleUrl: './lembrancinhas.component.css',
})
export class LembrancinhasComponent implements OnInit {
  listaLembrancinhas: any;

  ngOnInit(): void {
    this.listaLembrancinhas = [
      {
        id: 1,
        ativo: true,
        titulo: 'Balões',
        descricao: null,
        valor: 2.5  ,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/01.jpeg',
        recheio: null,
      },
      {
        id: 2,
        ativo: true,
        titulo: 'Ovinhos Recheados com Bala Fini',
        descricao: null,
        valor: 3,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/02.jpeg',
        recheio: null,
      },
      {
        id: 3,
        ativo: true,
        titulo: '2 mini ovos divertidos',
        descricao: null,
        valor: 3.5,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/03.jpeg',
        recheio: null,
      },

      {
        id: 4,
        ativo: false,
        titulo: 'Kit 6 Docinhos',
        descricao: null,
        valor: 3.5,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/04.jpeg',
        recheio: null,
      },
      {
        id: 5,
        ativo: true,
        titulo: 'Kit 3 Docinhos + 2 rabinhos de coelho',
        descricao: null,
        valor: 6.5,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/05.jpeg',
        recheio: null,
      },
      {
        id: 6,
        ativo: true,
        titulo: 'Controle Recheado',
        descricao: null,
        valor: 9,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/06.jpeg',
        recheio: null,
      },
      {
        id: 7,
        ativo: true,
        titulo: '6 docinhos + 2 mini ovos divertidos',
        descricao: null,
        valor: 5.5,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/07.jpeg',
        recheio: null,
      },
      {
        id: 8,
        ativo: false,
        titulo: '2 controles divertidos',
        descricao: null,
        valor: 12,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/08.jpeg',
        recheio: null,
      },
      {
        id: 9,
        ativo: true,
        titulo: '4 mini ovos divertidos',
        descricao: null,
        valor: 10,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/09.jpeg',
        recheio: null,
      },
      {
        id: 10,
        ativo: true,
        titulo: 'kit docinhos',
        descricao: 'kit com 4',
        descricao2: null,
        valor: 4,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/10.jpeg',
        recheio: null,
      },
      {
        id: 11,
        ativo: true,
        titulo: 'kit 8 docinhos',
        descricao: null,
        descricao2: null,
        valor: 5,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/11.jpeg',
        recheio: null,
      },
      {
        id: 12,
        ativo: true,
        titulo: 'kit 6 docinhos',
        descricao: null,
        descricao2: null,
        valor: 12,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/12.jpeg',
        recheio: null,
      },
      {
        id: 13,
        ativo: true,
        titulo: '3 coelhos recheados',
        descricao: null,
        descricao2: null,
        valor: 15,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/13.jpeg',
        recheio: null,
      },

      {
        id: 14,
        ativo: true,
        titulo: 'Cenouritos',
        descricao: '1 unidade',
        descricao2: null,
        valor: 29,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/14.jpeg',
        recheio: null,
      },
      {
        id: 15,
        ativo: true,
        titulo: '4 docinhos',
        descricao: null,
        descricao2: null,
        valor: 16,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/15.jpeg',
        recheio: null,
      },
      {
        id: 16,
        ativo: true,
        titulo: '',
        descricao: 'Docinho com coelhinho',
        descricao2: null,
        valor: 12,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/16.jpeg',
        recheio: null,
      },
      {
        id: 17,
        ativo: true,
        titulo: 'unidade bombom',
        descricao: null,
        descricao2: null,
        valor: 14,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/17.jpeg',
        recheio: null,
      },
      {
        id: 18,
        ativo: true,
        titulo: 'mini ovinho com embalagem coelhinho',
        descricao: null,
        descricao2: null,
        valor: 14,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/18.jpeg',
        recheio: null,
      },
      {
        id: 19,
        ativo: true,
        titulo: 'Bombons sortidos',
        descricao: null,
        descricao2: null,
        valor: 29,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/19.jpeg',
        recheio: null,
      },
      {
        id: 20,
        ativo: true,
        titulo: 'Bombons sortidos',
        descricao: null,
        descricao2: null,
        valor: 18,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/20.jpeg',
        recheio: null,
      },

      {
        id: 21,
        ativo: true,
        titulo: 'Mini cenouritos',
        descricao: null,
        descricao2: null,
        valor: 25,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/21.jpeg',
        recheio: null,
      },
      {
        id: 22,
        ativo: false,
        titulo: 'Ovo Frito',
        descricao: null,
        descricao2: null,
        valor: 20,
        peso: null,
        valor2: null,
        peso2: null,
        valor3: null,
        peso3: null,
        urlFoto: 'assets/lembrancinhas2025/22.jpeg',
        recheio: null,
      },
          ];
  }
}
